# Generated by theme-switch.sh — do not edit by hand
[main]
font=Noto Sans Mono:size=11
dpi-aware=auto
width=40
lines=15
exit-on-keyboard-focus-loss=no

[colors]
background=${BASE}dd
text=${TEXT}ff
prompt=${SUBTEXT1}ff
placeholder=${MUTE}ff
input=${TEXT}ff
match=${ACCENT}ff
selection=${SURFACE2}ff
selection-text=${TEXT}ff
selection-match=${ACCENT}ff
counter=${MUTE}ff
border=${ACCENT}ff
