# Generated by theme-switch.sh — do not edit by hand
# class                 border    background text      indicator child_border
client.focused          #${ACCENT}   #${SURFACE0}    #${TEXT}   #${ACCENT}   #${ACCENT}
client.focused_inactive #${OVERLAY0}   #${SURFACE0}    #${SUBTEXT1}   #${OVERLAY0}   #${OVERLAY0}
client.unfocused        #${SURFACE2}   #${BASE}    #${SUBTEXT0}   #${SURFACE2}   #${SURFACE2}
client.urgent           #${RED}   #${RED}    #${BASE}   #${RED}   #${RED}
client.placeholder      #${SURFACE1}   #${BASE}    #${SUBTEXT0}   #${SURFACE1}   #${SURFACE1}
