/* Generated by theme-switch.sh — do not edit by hand */

* {
    font-family: 'Noto Sans Mono', 'Font Awesome 6 Free', 'Font Awesome 6 Brands', monospace;
    font-size: 13px;
}

window#waybar {
    background-color: rgba(${BASE_R}, ${BASE_G}, ${BASE_B}, 0.92);
    border-bottom: 2px solid rgba(${OVL0_R}, ${OVL0_G}, ${OVL0_B}, 0.65);
    color: #${TEXT};
    transition-property: background-color;
    transition-duration: 0.3s;
}

window#waybar.hidden {
    opacity: 0.2;
}

window#waybar.termite {
    background-color: #${SURFACE0};
}

window#waybar.chromium {
    background-color: #000000;
    border: none;
}

button {
    box-shadow: inset 0 -2px transparent;
    border: none;
    border-radius: 0;
}

button:hover {
    background: inherit;
    box-shadow: inset 0 -2px #${ACCENT};
}

#workspaces button {
    padding: 0 5px;
    background-color: transparent;
    color: #${TEXT};
}

#workspaces button:hover {
    background: rgba(${ACCENT_R}, ${ACCENT_G}, ${ACCENT_B}, 0.18);
}

#workspaces button.focused {
    background-color: #${SURFACE1};
    box-shadow: inset 0 -2px #${ACCENT};
}

#workspaces button.urgent {
    background-color: #${RED};
    color: #${BASE};
}

#mode {
    background-color: #${SURFACE2};
    box-shadow: inset 0 -2px #${MAUVE};
}

#clock,
#battery,
#cpu,
#memory,
#disk,
#temperature,
#backlight,
#network,
#pulseaudio,
#wireplumber,
#custom-media,
#tray,
#mode,
#idle_inhibitor,
#scratchpad,
#power-profiles-daemon,
#custom-power,
#mpd {
    padding: 0 10px;
    background-color: #${SURFACE0};
    color: #${TEXT};
}

#window,
#workspaces {
    margin: 0 4px;
}

.modules-left > widget:first-child > #workspaces {
    margin-left: 0;
}

.modules-right > widget:last-child > #workspaces {
    margin-right: 0;
}

#battery.charging,
#battery.plugged {
    background-color: #${GREEN};
    color: #${BASE};
}

@keyframes blink {
    to {
        opacity: 0.65;
    }
}

#battery.critical:not(.charging) {
    background-color: #${RED};
    color: #${BASE};
    animation-name: blink;
    animation-duration: 0.5s;
    animation-timing-function: steps(12);
    animation-iteration-count: infinite;
    animation-direction: alternate;
}

#power-profiles-daemon {
    padding-right: 15px;
}

#power-profiles-daemon.performance,
#power-profiles-daemon.balanced,
#power-profiles-daemon.power-saver {
    background-color: #${SURFACE0};
    color: #${TEXT};
}

label:focus {
    background-color: #${SURFACE0};
}

#network.disconnected {
    background-color: #${PEACH};
    color: #${BASE};
}

#pulseaudio:hover,
#cpu:hover,
#memory:hover,
#clock:hover,
#network:hover,
#temperature:hover,
#idle_inhibitor:hover,
#custom-power:hover,
#tray:hover {
    background-color: #${SURFACE1};
}

#pulseaudio.muted {
    background-color: #${SURFACE0};
    color: #${MUTE};
}

#wireplumber.muted {
    background-color: #${RED};
    color: #${BASE};
}

#custom-media {
    min-width: 100px;
}

#custom-media.custom-spotify,
#custom-media.custom-vlc {
    background-color: #${SURFACE0};
    color: #${TEXT};
}

#temperature.critical {
    background-color: #${YELLOW};
    color: #${BASE};
}

#tray > .passive {
    -gtk-icon-effect: dim;
}

#tray > .needs-attention {
    -gtk-icon-effect: highlight;
    background-color: #${RED};
}

#idle_inhibitor.activated {
    background-color: #${MAUVE};
    color: #${BASE};
}

#mpd.disconnected {
    background-color: #${RED};
    color: #${BASE};
}

#mpd.stopped,
#mpd.paused {
    background-color: #${SURFACE0};
    color: #${TEXT};
}

#language {
    background: #${SURFACE0};
    color: #${TEXT};
    padding: 0 5px;
    margin: 0 5px;
    min-width: 16px;
}

#keyboard-state {
    background: #${SURFACE0};
    color: #${TEXT};
    padding: 0 0;
    margin: 0 5px;
    min-width: 16px;
}

#keyboard-state > label {
    padding: 0 5px;
}

#keyboard-state > label.locked {
    background: #${SURFACE2};
}

#scratchpad.empty {
    background-color: transparent;
}

#privacy {
    padding: 0;
}

#privacy-item {
    padding: 0 5px;
    color: #${TEXT};
}

#privacy-item.screenshare,
#privacy-item.audio-in,
#privacy-item.audio-out {
    background-color: #${SURFACE0};
    color: #${TEXT};
}
