#!/usr/bin/env bash
set -euo pipefail

CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/waybar"
STYLE_FILE="$CFG_DIR/style.css"
DESKTOP_SESSION_NAME="${XDG_CURRENT_DESKTOP:-${DESKTOP_SESSION:-}}"
DESKTOP_SESSION_NAME="${DESKTOP_SESSION_NAME,,}"
WAYBAR_ACTIVE_CONFIG=""

detect_waybar_active_config() {
  local pid cmdline prev=""
  pid="$(pgrep -xo waybar 2>/dev/null || true)"
  [[ -n "$pid" ]] || return 1
  [[ -r "/proc/$pid/cmdline" ]] || return 1
  cmdline="$(tr '\0' '\n' <"/proc/$pid/cmdline" 2>/dev/null || true)"
  [[ -n "$cmdline" ]] || return 1
  while IFS= read -r tok; do
    if [[ "$prev" == "-c" && -n "$tok" ]]; then
      WAYBAR_ACTIVE_CONFIG="$tok"
      return 0
    fi
    prev="$tok"
  done <<<"$cmdline"
  return 1
}

if detect_waybar_active_config && [[ -f "$WAYBAR_ACTIVE_CONFIG" ]]; then
  CONFIG_FILE="$WAYBAR_ACTIVE_CONFIG"
  if [[ "$CONFIG_FILE" == *"config-hyprland.jsonc" ]]; then
    SESSION_KEY="hyprland"
  elif [[ "$CONFIG_FILE" == *"config.jsonc" ]]; then
    SESSION_KEY="sway"
  else
    SESSION_KEY="active"
  fi
elif [[ -n "${SWAYSOCK:-}" ]] || [[ "$DESKTOP_SESSION_NAME" == *"sway"* ]]; then
  CONFIG_FILE="$CFG_DIR/config.jsonc"
  SESSION_KEY="sway"
elif [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] || [[ "$DESKTOP_SESSION_NAME" == *"hypr"* ]]; then
  CONFIG_FILE="$CFG_DIR/config-hyprland.jsonc"
  SESSION_KEY="hyprland"
else
  # Best-effort fallback: prefer hyprland config if running Hyprland process.
  if pgrep -x Hyprland >/dev/null 2>&1 && [[ -f "$CFG_DIR/config-hyprland.jsonc" ]]; then
    CONFIG_FILE="$CFG_DIR/config-hyprland.jsonc"
    SESSION_KEY="hyprland"
  else
    CONFIG_FILE="$CFG_DIR/config.jsonc"
    SESSION_KEY="default"
  fi
fi
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/swaydots"
BASE_FILE="$STATE_DIR/waybar-style.base.css"
BASE_CONFIG_FILE="$STATE_DIR/waybar-config.${SESSION_KEY}.base.jsonc"
LAST_STYLE_FILE="$STATE_DIR/waybar-style.last.css"
LAST_CONFIG_FILE="$STATE_DIR/waybar-config.${SESSION_KEY}.last.jsonc"
STYLES_DIR="$CFG_DIR/styles"
mkdir -p "$STATE_DIR"

notify() {
  command -v notify-send >/dev/null 2>&1 && notify-send -a "swaydots" "Waybar style" "$1" || true
}

reload_waybar() {
  # First try in-place reload.
  pkill -SIGUSR2 waybar 2>/dev/null || true
  sleep 0.15
  if pgrep -x waybar >/dev/null 2>&1; then
    return 0
  fi
  # If no waybar process is alive, start one explicitly.
  if [[ -x "$CFG_DIR/launch.sh" ]]; then
    nohup "$CFG_DIR/launch.sh" >/dev/null 2>&1 &
  else
    nohup waybar >/dev/null 2>&1 &
  fi
}

if ! command -v fuzzel >/dev/null 2>&1; then
  echo "waybar-style-picker: fuzzel not found" >&2
  notify "fuzzel not found"
  exit 1
fi

if [[ ! -f "$STYLE_FILE" ]]; then
  echo "waybar-style-picker: missing $STYLE_FILE" >&2
  notify "missing $STYLE_FILE"
  exit 1
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "waybar-style-picker: missing $CONFIG_FILE" >&2
  notify "missing $CONFIG_FILE"
  exit 1
fi

if [[ ! -w "$STYLE_FILE" ]]; then
  echo "waybar-style-picker: $STYLE_FILE is not writable" >&2
  notify "style.css is not writable"
  exit 1
fi

if [[ ! -w "$CONFIG_FILE" ]]; then
  echo "waybar-style-picker: $CONFIG_FILE is not writable" >&2
  notify "config is not writable"
  exit 1
fi

if ! sed -n '1p' "$STYLE_FILE" | rg -q "Generated by waybar-style-picker.sh"; then
  cp -f "$STYLE_FILE" "$BASE_FILE"
elif [[ ! -f "$BASE_FILE" ]]; then
  cp -f "$STYLE_FILE" "$BASE_FILE"
fi

if ! sed -n '1p' "$CONFIG_FILE" | rg -q "Generated by waybar-style-picker.sh"; then
  cp -f "$CONFIG_FILE" "$BASE_CONFIG_FILE"
elif [[ ! -f "$BASE_CONFIG_FILE" ]]; then
  cp -f "$CONFIG_FILE" "$BASE_CONFIG_FILE"
fi

restore_base_layout() {
  cp -f "$BASE_CONFIG_FILE" "$CONFIG_FILE"
}

snapshot_current() {
  cp -f "$STYLE_FILE" "$LAST_STYLE_FILE"
  cp -f "$CONFIG_FILE" "$LAST_CONFIG_FILE"
}

restore_last_snapshot() {
  if [[ -f "$LAST_STYLE_FILE" && -f "$LAST_CONFIG_FILE" ]]; then
    cp -f "$LAST_STYLE_FILE" "$STYLE_FILE"
    cp -f "$LAST_CONFIG_FILE" "$CONFIG_FILE"
    return 0
  fi
  return 1
}

sanitize_preset_css() {
  local preset="$1"
  python3 - "$preset" <<'PY'
import pathlib
import re
import sys
p = pathlib.Path(sys.argv[1])
text = p.read_text()
out = []
for line in text.splitlines():
    s = line.strip().lower()
    if "color:" in s or "background:" in s or "background-color:" in s or "border-color:" in s:
        continue
    if re.search(r'#[0-9a-f]{3,8}\b', s):
        continue
    if "rgb(" in s or "rgba(" in s or "hsl(" in s or "hsla(" in s:
        continue
    out.append(line)
print("\n".join(out))
PY
}

apply_layout_profile() {
  local profile="$1"
  local target_cfg="$2"
  python3 - "$target_cfg" "$profile" <<'PY'
import pathlib
import re
import sys

cfg = pathlib.Path(sys.argv[1])
profile = sys.argv[2]
text = cfg.read_text()
is_hypr = '"hyprland/workspaces"' in text
ws = "hyprland/workspaces" if is_hypr else "sway/workspaces"
win = "hyprland/window" if is_hypr else "sway/window"
mode = "hyprland/submap" if is_hypr else "sway/mode"
scratch = None if is_hypr else "sway/scratchpad"

def arr(items):
    return ",\n".join(f'        "{item}"' for item in items if item)

profiles = {
    # Very compact status-right layout.
    "minimal": {
        "left": [ws],
        "center": [],
        "right": ["clock", "pulseaudio", "tray", "custom/power"],
    },
    # Balanced "glass" look with centered media.
    "glass": {
        "left": [ws, mode, scratch],
        "center": ["custom/media", win],
        "right": ["network", "pulseaudio", "clock", "tray", "custom/power"],
    },
    # Dock-like: app/media emphasis left, centered clock.
    "macios": {
        "left": [ws, "custom/media", win],
        "center": ["clock"],
        "right": ["pulseaudio", "cpu", "memory", "temperature", "tray", "custom/power"],
    },
    # Taskbar-like: window title left, utilities right.
    "windows": {
        "left": [ws, win],
        "center": [],
        "right": ["custom/media", "network", "pulseaudio", "clock", "tray", "custom/power"],
    },
    # Clean centered clock and short right stack.
    "sleek": {
        "left": [ws, win],
        "center": ["clock"],
        "right": ["custom/media", "pulseaudio", "tray", "custom/power"],
    },
    # Widget-heavy center with mode/scratch left.
    "chiclets": {
        "left": [ws, mode, scratch],
        "center": ["custom/media", win],
        "right": ["cpu", "memory", "temperature", "clock", "custom/power"],
    },
    # Strong split: media/workspaces left, title center, stats right.
    "split": {
        "left": [ws, "custom/media"],
        "center": [win],
        "right": ["network", "pulseaudio", "cpu", "memory", "temperature", "clock", "custom/power"],
    },
    # Monochrome/utility minimalism.
    "mono": {
        "left": [ws, mode],
        "center": [win],
        "right": ["pulseaudio", "clock", "custom/power"],
    },
    # Full info-dense bar.
    "dense": {
        "left": [ws, mode, scratch, win],
        "center": ["custom/media"],
        "right": ["idle_inhibitor", "power-profiles-daemon", "network", "pulseaudio", "cpu", "memory", "temperature", "clock", "tray", "custom/power"],
    },
}

if profile not in profiles:
    print(f"waybar-style-picker: unknown layout profile '{profile}'", file=sys.stderr)
    sys.exit(1)

p = profiles[profile]
modules_left = '    "modules-left": [\n' + arr(p["left"]) + '\n    ],'
modules_center = '    "modules-center": [\n' + arr(p["center"]) + '\n    ],'
modules_right = '    "modules-right": [\n' + arr(p["right"]) + '\n    ],'

def replace_array(src: str, key: str, replacement: str) -> str:
    pattern = rf'^\s*"{re.escape(key)}"\s*:\s*\[[\s\S]*?\],'
    out, count = re.subn(pattern, replacement, src, count=1, flags=re.M)
    if count != 1:
        raise RuntimeError(f"could not patch {key} array")
    return out

try:
    text = replace_array(text, "modules-left", modules_left)
    text = replace_array(text, "modules-center", modules_center)
    text = replace_array(text, "modules-right", modules_right)
except RuntimeError as e:
    print(f"waybar-style-picker: {e}", file=sys.stderr)
    sys.exit(1)

text = f'/* Generated by waybar-style-picker.sh ({profile} layout) */\n{text}'
cfg.write_text(text)
PY
}

apply_layout_everywhere() {
  local profile="$1"
  local -a targets=("$CONFIG_FILE")
  local alt_cfg=""
  if [[ "$CONFIG_FILE" == *"config-hyprland.jsonc" ]]; then
    alt_cfg="$CFG_DIR/config.jsonc"
  else
    alt_cfg="$CFG_DIR/config-hyprland.jsonc"
  fi
  if [[ -f "$alt_cfg" && "$alt_cfg" != "$CONFIG_FILE" ]]; then
    targets+=("$alt_cfg")
  fi

  local t
  for t in "${targets[@]}"; do
    if [[ -w "$t" ]]; then
      apply_layout_profile "$profile" "$t"
    fi
  done
}

choice="$(
  printf '%s\n' \
    "default" \
    "restore-last" \
    "minimal" \
    "glass" \
    "macios" \
    "windows" \
    "sleek" \
    "chiclets" \
    "split" \
    "mono" \
    "dense" \
  | fuzzel --dmenu --prompt "Waybar style: "
)"

[[ -z "${choice:-}" ]] && exit 0

case "$choice" in
  default)
    snapshot_current
    cp -f "$BASE_FILE" "$STYLE_FILE"
    restore_base_layout
    ;;
  restore-last)
    if ! restore_last_snapshot; then
      notify "No previous snapshot found"
      exit 1
    fi
    ;;
  minimal|glass|macios|windows|sleek|chiclets|split|mono|dense)
    snapshot_current
    preset="$STYLES_DIR/${choice}.css"
    if [[ ! -f "$preset" ]]; then
      echo "waybar-style-picker: preset not found: $preset" >&2
      notify "preset not found: $choice"
      exit 1
    fi
    {
      printf '/* Generated by waybar-style-picker.sh (%s) */\n\n' "$choice"
      cat "$BASE_FILE"
      printf '\n\n/* --- style preset: %s --- */\n\n' "$choice"
      sanitize_preset_css "$preset"
    } >"$STYLE_FILE"
    restore_base_layout
    apply_layout_everywhere "$choice"
    ;;
  *)
    exit 0
    ;;
esac

reload_waybar
notify "Applied: $choice ($SESSION_KEY)"
