# Catppuccin Mocha — matches Sway / waybar theme
include mocha.conf

font_family      Noto Sans Mono
font_size        11.0
bold_font        auto
italic_font      auto
bold_italic_font auto

shell .
cursor_shape     beam
scrollback_lines 10000
enable_audio_bell no
