# vim:ft=kitty
# Catppuccin Frappe
foreground #c6d0f5
background #303446
selection_foreground #303446
selection_background #8caaee
cursor #f2d5cf
cursor_text_color #303446
url_color #8caaee
active_border_color #8caaee
inactive_border_color #737994
color0 #51576d
color8 #626880
color1 #e78284
color9 #e78284
color2 #a6d189
color10 #a6d189
color3 #e5c890
color11 #e5c890
color4 #8caaee
color12 #8caaee
color5 #ca9ee6
color13 #ca9ee6
color6 #81c8be
color14 #81c8be
color7 #b5bdae
color15 #a5adce
